/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Orange Flower.glb -T 
Files: Orange Flower.glb [282.35KB] > F:\My Documents\Sites\games\tag\public\models\Orange Flower-transformed.glb [36.76KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Orange Flower-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.hibiscus_flower.geometry} material={materials.red} />
    </group>
  )
}

useGLTF.preload('/Orange Flower-transformed.glb')
