/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Cannon/Cannon.glb`

export function Cannon(props) {
    const { nodes, materials } = useGLTF(link)
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Prop_Cannon.geometry}
                material={materials.Atlas}
                scale={100}
            />
        </group>
    )
}