/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Cone, Cylinder, useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/duck.gltf`

export default function Duck(props) {

    const { color, isIt } = props;

    const { nodes, materials } = useGLTF(link);

    const originalMaterial = materials["White.026"];
    const newMaterial = originalMaterial.clone();

    // TODO - Check if valid hex then set color?

    if (color) {
        newMaterial.color.set(color);
    }

    return (
        <group {...props} dispose={null}>

            <mesh position={[0, 0, 0]}>
                <cylinderGeometry args={[1, 1, 5, 100]} />
                <meshStandardMaterial
                    color={color}
                    transparent={true}
                    opacity={0.5}
                />
            </mesh>

            {isIt &&
                <group>
                    <Cylinder
                        position={[0, 3.25, 0]}
                        args={[0.25, 0.25, 2, 8]}
                        material-color="red"
                    />
                    <Cone
                        position={[0, 2.25, 0]}
                        args={[0.5, 1, 10]}
                        material-color="red"
                        rotation={[Math.PI / 1, 0, 0]}
                        castShadow
                        receiveShadow
                    />
                </group>
            }

            <mesh
                castShadow
                receiveShadow
                geometry={nodes.character_duck.geometry}
                material={newMaterial}
                rotation={[Math.PI / 2, 0, 0]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.character_duckArmLeft.geometry}
                    material={newMaterial}
                    position={[0.204, 0, -0.634]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.character_duckArmRight.geometry}
                    material={newMaterial}
                    position={[-0.204, 0, -0.634]}
                />
                <group position={[0, 0, -0.704]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1338.geometry}
                        material={newMaterial}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1338_1.geometry}
                        material={materials["Yellow.043"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1338_2.geometry}
                        material={materials["Black.027"]}
                    />
                </group>
            </mesh>
        </group>
    );
}

useGLTF.preload(link);