/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Cannon/Farm.glb`

export function Farm(props) {
    const { nodes, materials } = useGLTF(link)
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Farm.geometry} material={materials.Mat} />
        </group>
    )
}

useGLTF.preload('/Farm.glb')
