/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Cannon/Paint Bucket.glb`

export function PaintBucket(props) {
    const { nodes, materials } = useGLTF(link)
    return (
        <group {...props} dispose={null}>
            <group scale={100}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Paint_Bucket_1.geometry}
                    material={materials.mat16}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Paint_Bucket_2.geometry}
                    material={materials.mat8}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Paint_Bucket_3.geometry}
                    material={materials.mat4}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Paint_Bucket_4.geometry}
                    material={materials.mat15}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Paint_Bucket_5.geometry}
                    material={materials.mat19}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/Paint Bucket.glb')
